### PR TITLE
Packages plugin

### PR DESCRIPTION
**Pull request by sh9189**
This PR continues implementation of packages plugin from #570 and adds support for AIX, Solaris platforms as well as tests for windows platform. Thanks to @cmluciano for the initial PR.

### CODE REVIEW

**Comment by johnbellone** [comment]
:+1:

**Comment by sh9189** [comment]
@MarkGibbons yes that's debugging code, but it was removed in 35740cfad4b52d2f3a54f17932ce341ee2e80f76 and is not part of the pull request

**Comment by sh9189** [comment]
@mcquin Can you please take a look at this since you also reviewed #570 ?

**Comment by mcquin** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by cmluciano** [comment]
\o/

**Pull request merged**
