### PR TITLE
Improve KVM host and guest detection

### PR DESCRIPTION
**Pull request by tas50**
Before we detected KVM hosts via kvm modules, which are actually loaded for both guests and hosts.  Instead use /sys/devices/virtual/misc/kvm to determine if the system is KVM in anyway.  From there look for a hypervisor cpu feature flag to determine if we're a guest.  If that isn't there we're on a host.

### CODE REVIEW

**Comment by tas50** [comment]
This resolves #749

**Comment by thommay** [comment]
you really are turning into the cloud whisperer. :+1:

**Comment by tas50** [comment]
@chef/client-core this is ready for review

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
