### PR TITLE
Add a simple plugin to get the local timezone.

### PR DESCRIPTION
**Pull request by johnbellone**
We have an internal plugin where we are doing the same thing, and we were a little surprised that this didn't exist yet. I didn't think there was a better namespace place to shove this under.

### CODE REVIEW

**Comment by thommay** [comment]
@smurawaski can you take a look at the powershell failures in appveyor please?

**Comment by mcquin** [comment]
@johnbellone Great addition! Since we don't have a lot of other plugins collecting time information, I don't feel like trying to nest this under a `Time` plugin makes sense (it was my initial thought, but we don't have a good enough understanding of what the data we want to collect will look like). If we do decide to scope this under another plugin, we can add it as a dependency.

:+1: ⌚

**Comment by johnbellone** [comment]
@mcquin Sounds good to me.

**Comment by tas50** [comment]
👍

**Comment by lamont-granquist** [comment]
so this probably breaks half the timezone cookbooks out there in the rest of the world.

`node.automatic["timezone"]` will override `node.default["timezone"]` in any cookbook.  lots of those use a sub-hash to configure things so it'll obliterate the "schema"

https://github.com/L2G/timezone-ii/blob/master/attributes/default.rb#L7-L15

in my own cookbooks I use `node.default["timezone"]["value"]`  and now my runs crash with:

```
  NoMethodError
  -------------
  undefined method `value' for "PDT":String
```

**Comment by lamont-granquist** [comment]
yeah i think unfortunately, i'm going to whack revert on this, i don't think we want this going out in the next chef release without more discussion

**Comment by johnbellone** [comment]
No worries, makes sense to me. Do you want to leave it open?

**Comment by tas50** [comment]
@johnbellone We moved everything under node['time'] and shipped 8.17.1. It's all good now

**Pull request merged**
