### PR TITLE
Refactor DigitalOcean plugin to use DigitalOcean Metadata API

### PR DESCRIPTION
**Pull request by GenPage**
Here's my first iteration that I've done. I've ripped out the old network/interface code in place of the metadata information. About half of the tests are passing right now, still working on that. Please let me know if there is anything I am missing or something that stands out to anyone that should be done better/differently. :smile: 

This is a follow-up to #649

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @GenPage

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
There's some chefstyle (our rubocop wrapper) warnings.  Run chefstyle -a on your files to fixup those warnings.

**Comment by gregf** [comment]
@GenPage are you still working on this?

**Comment by GenPage** [comment]
@tas50 @gregf Yes I am, I apologize for the lack of response. Personal and work responsibility have put this on the back burner. The functionality should work, but just having a little trouble drafting up optimal test cases and some chef style errors to fix

**Comment by tas50** [comment]
@GenPage Thanks for all the work on this. It hasn't been forgotten. I forked off this in #823 and changed things up a bit. Since it changes / breaks the existing behavior (but in a good way) we're going to hold off on merging this until we release Chef 13 next April. Please take a look at the new PR and let me know if that'll work for folks at DO and you're customers.

**Pull request closed without merging**
