### PR TITLE
Add additional info to networking interfaces/addresses

### PR DESCRIPTION
**Pull request by jaymzh**
I'd like to know if addresses are dynamic or not, for example.

### CODE REVIEW

**Comment by jaymzh** [comment]
CC @chef/client-core 
Also... does app-veyer ever work?

**Comment by smurawski** [comment]
@jaymzh Yeah, appveyor has been having a rough week or so with our code.There is a broken functional test because of how we parsed out the powershell compatible versions which broke when we went from powershell 4 to 5 on the build agents.  (https://github.com/chef/ohai/issues/831).  This new error seems to be releated to the rubygems version (at least that's the only difference I see with test runs that pass and fail.  I'm troubleshooting in a PR against test-kitchen).

**Comment by smurawski** [comment]
Oh and :+1: on the PR

**Comment by mcquin** [comment]
LGTM 🚀

**Comment by tas50** [comment]
👍

**Pull request merged**
