### PR TITLE
Prep for release 8.9.0

### PR DESCRIPTION
**Pull request by chefsalim**
@chef/client-maintainers @tas50 @jkeiser

### CODE REVIEW

**Comment by jkeiser** [comment]
:+1:

**Comment by sersut** [comment]
:+1:

**Comment by btm** [comment]
:+1: 

it'd be good to test that ipaddress, macaddress, ip6address return the same thing on a couple hosts as they do with 8.8.1

**Comment by tas50** [comment]
We need some release notes specifically for the ipv6 changes

**Comment by btm** [comment]
`$ for a in -v ipaddress macaddress ip6address ; do ohai $a ; done` shows the same results for me on:

Ubuntu 14.04 LTS
Mac OS X 10.11.2
Windows 10 Pro

**Pull request merged**
