### PR TITLE
use bundle rake tasks

### PR DESCRIPTION
**Pull request by thommay**
cc @chef/client-core

### CODE REVIEW

**Comment by jaym** [comment]
:+1:

**Comment by danielsdeleo** [comment]
@thommay does this change the names of the tasks? Could have an impact on Ci if so.

**Comment by thommay** [comment]
It changes the `:gem` task to `:build` and removes `:package`. Omnibus uses `gem build` directly, travis uses `rake spec` and Appveyor uses `:default` which is an alias to `:spec`. So I don't think it's a problem, but I'll keep an eye out for failing Jenkins.

**Comment by danielsdeleo** [comment]
ok, cool.

**Pull request merged**
