### PR TITLE
Fix false detection of Linux hosts with a DHCP lease as being azure

### PR DESCRIPTION
**Pull request by tas50**
The presence of a DHCP lease file was enough to match as Azure.  Fix that and add a test with an Openstack DHCP lease so this doesn't happen again.

### CODE REVIEW

**Comment by tas50** [comment]
We'll need to get this one merged before we ship the next Ohai otherwise everyone is going to look like they're on a cloud host.

**Comment by thommay** [comment]
:+1:

**Comment by jkeiser** [comment]
:+1:

**Comment by jkeiser** [comment]
Excluding from changelog since it's not a change from the last release.

**Pull request merged**
