### PR TITLE
Add support for opensuse leap

### PR DESCRIPTION
**Pull request by spuranam**
This fix address install failures of latest version chef server, chef reporting, chef manage and likely other products.

### CODE REVIEW

**Comment by tas50** [comment]
Is Leap enough like Enterprise that identifying leap as enterprise would satisfy everyone?

**Comment by spuranam** [comment]
[OpenSuse Leap tacks SLES](https://news.opensuse.org/2015/11/04/opensuse-leap-42-1-becomes-first-hybrid-distribution/), just like Centos tracks RHEL hence it should be safe to make that assumption.

**Comment by tas50** [comment]
:+1:

**Comment by lamont-granquist** [comment]
so i'm :-1: on returning `suse` for node[:platform] because it is NOT SLES.  it is a distribution built on top of SLES.  the platform probably needs to be 'opensuse' or 'leap' or or 'suseleap' or something else that makes sense there that isn't 'suse' (which means SLES in our world).  this isn't a CentOS-RHEL because CentOS is pretty much /identically/ RHEL (there was that period when they shipped yum and redhat didn't but that stopped back in RHEL4 days).  and anyway we still have a platform of 'centos' for it.

**Comment by tas50** [comment]
@lamont-granquist has shown me the light here.  We probably want to make a platform of suseleap that maps to the suse platform_family since this is similar but different than suse.

**Comment by lamont-granquist** [comment]
definitely :+1: on `suse` for platform_family.

**Comment by tas50** [comment]
Closing this in favor of #784

**Pull request closed without merging**
