### PR TITLE
Remove redundant if statement

### PR DESCRIPTION
**Pull request by Maniacal**
Removing redundant if statement

### CODE REVIEW

**Comment by mcquin** [comment]
:+1:

**Comment by smurawski** [comment]
@btm @lamont-granquist @danielsdeleo Can we get another +1 and merge?

**Comment by btm** [comment]
:+1:

**Comment by btm** [comment]
Rebased and merged as 12ae73945d776b0afbaa96835276cf9151425d62,, thanks @Maniacal!

**Pull request closed without merging**
