### PR TITLE
Add swap space attributes for AIX

### PR DESCRIPTION
**Pull request by sh9189**
This PR adds swap space attributes for AIX as found in memory plugins for other platforms

### CODE REVIEW

**Comment by johnbellone** [comment]
:+1:

**Comment by johnbellone** [comment]
@irvingpop

**Comment by liutc** [comment]
Is there any special reason to return the swap size in 4K blocks? Why not in MB or KB?

**Comment by thommay** [comment]
@lamont-granquist can you take a look? The 4k blocks thing does seem weird but maybe that's an AIXism?

**Comment by lamont-granquist** [comment]
looks like its a JFS2-ism.  it looks like it can be tuned differently but i doubt anyone does for swap partitions?

i think i'm okay with merging as-is and letting bug reports find any edge conditions with different filesystems and different tunings since i suspect those edge conditions won't occur enough and worrying about dynamically determining the fs blocksize of the swap partition will be YAGNI.

**Comment by lamont-granquist** [comment]
so :+1:

**Comment by liutc** [comment]
Why shouldn't we use the "size" in KB or MB? Other platforms use KB (at
least for Linux).

We do not need to handle that by ourself the block size thing. See below
output from one AIX box I manage. If we use "swap -l", we just get the size
and do a sum will be all good.

swap -l
device              maj,min        total       free
/dev/paging01         38,  3      1024MB      1023MB
/dev/paging00         37,  4      1280MB      1279MB
/dev/paging02         39,  3       128MB       124MB
/dev/hd6              10,  2      2560MB      2551MB

swap -s
allocated  =    1277952 blocks    used  =   3432 blocks      free  =
1274520 blocks



Best Regards,

Dr. Tiancheng Liu (?$BE7@.(B)

Cloud Operations Technology
IBM Research - China

Phone: (86-10)58748521
Fax:   (86-10)58748731
Email: liutc@cn.ibm.com

Address: Building 19 Zhongguancun Software Park, 8 Dongbeiwang WestRoad,
Haidian District, Beijing, P.R. China
Beijing 100193

**Comment by lamont-granquist** [comment]
@liutc can you submit a patch for that?

**Pull request merged**
