### PR TITLE
Cleanup attribute access in cloud plugins

### PR DESCRIPTION
**Pull request by tas50**
Use get_attribute to simplify code in places where we previously had to rescue NoMethodError

### CODE REVIEW

**Comment by tas50** [comment]
Ready for review @chef/client-core

**Comment by mcquin** [comment]
👍

**Comment by tas50** [comment]
Care to take a look @thommay

**Comment by thommay** [comment]
technically you and claire were enough eyes on this (two maintainers), but 👍 regardless

**Pull request merged**
