### PR TITLE
Update changelog, bump version

### PR DESCRIPTION
**Pull request by chefsalim**
Prep for release of Ohai 8.9.1

@chef/client-core @tas50 @danielsdeleo @jaym

### CODE REVIEW

**Comment by danielsdeleo** [comment]
@chefsalim mine's not merged yet but should be soon

**Comment by jaym** [comment]
Let's hold off until @danielsdeleo merges

**Comment by chefsalim** [comment]
Yeah I'll rebase, this is just prep :)

**Comment by lamont-granquist** [comment]
8.10.0 instead of 8.9.1?  its not a big release, but they're not strictly bugfixes...  dunno...

**Comment by chefsalim** [comment]
Seems like they're kind of fixes, as we are cleaning up after the last release..?

**Comment by tas50** [comment]
The ec2 thing is questionably a fix.  We did make an attempt to detect ec2 before and now we do a better job of it. It was *sorta* broken before.

**Comment by danielsdeleo** [comment]
The pnp thing technically should be a major bump but we're making a semver exception because of large negative value there. If we're including it, I'd prefer to do a minor bump (or we could even do a major bump for ohai but not for chef-client).

**Comment by lamont-granquist** [comment]
major bumps to ohai are pretty annoying to do because of pessimistic version constraints everywhere that'll need to get bumped...

**Comment by danielsdeleo** [comment]
Yeah, I'm fine with minor if we'd rather.

**Comment by btm** [comment]
:+1: on bumping minor instead of patch. it's free.

**Comment by jaym** [comment]
I vote for 8.10.0 as well

**Comment by jaym** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1: Make sure we're very clear about the PnP thing when we ship

**Pull request merged**
