### PR TITLE
Change windows cpu plugin to be consistent with other plaforms, add spec test

### PR DESCRIPTION
**Pull request by sh9189**
1. Change cpu[:total] to return total number of logical processors instead of cores as in other platforms like Linux,Solaris
2. Add cpu[:cores] to return total number of cores
3. Add spec tests for the cpu plugin on windows

### CODE REVIEW

**Comment by mcquin** [comment]
On my Windows 10 VM I'm seeing

```
Claire McQuin> bundle exec ohai cpu
{
  "0": {
    "cores": 2,
    "vendor_id": "GenuineIntel",
    "family": "2",
    "model": "14857",
    "stepping": null,
    "physical_id": "CPU0",
    "model_name": "Intel64 Family 6 Model 58 Stepping 9",
    "mhz": "2394",
    "cache_size": "0 KB"
  },
  "total": 2,
  "cores": 2,
  "real": 1
}
```

I think `cpu["0"]["stepping"]` should be `"9"`, correct?

**Comment by mcquin** [comment]
Never mind, that seems to be consistent with what I'm getting from WMI:

```
[1] pry(main)> require 'wmi-lite/wmi'
=> true
[2] pry(main)> wmi = WmiLite::Wmi.new
=> #<WmiLite::Wmi:0x00000002fa0170 @connection=nil, @namespace="root/cimv2">
[3] pry(main)> processors = wmi.instances_of('Win32_Processor')
=> [#<WmiLite::Wmi::Instance:0x000000044bc6a8
  @property_map=
   {"addresswidth"=>64,
    "architecture"=>9,
    "assettag"=>"",
    "availability"=>3,
    "caption"=>"Intel64 Family 6 Model 58 Stepping 9",
    "characteristics"=>nil,
    "configmanagererrorcode"=>nil,
    "configmanageruserconfig"=>nil,
    "cpustatus"=>1,
    "creationclassname"=>"Win32_Processor",
    "currentclockspeed"=>2394,
    "currentvoltage"=>33,
    "datawidth"=>64,
    "description"=>"Intel64 Family 6 Model 58 Stepping 9",
    "deviceid"=>"CPU0",
    "errorcleared"=>nil,
    "errordescription"=>nil,
    "extclock"=>nil,
    "family"=>2,
    "installdate"=>nil,
    "l2cachesize"=>0,
    "l2cachespeed"=>nil,
    "l3cachesize"=>0,
    "l3cachespeed"=>0,
    "lasterrorcode"=>nil,
    "level"=>6,
    "loadpercentage"=>1,
    "manufacturer"=>"GenuineIntel",
    "maxclockspeed"=>2394,
    "name"=>"Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz",
    "numberofcores"=>2,
    "numberofenabledcore"=>nil,
    "numberoflogicalprocessors"=>2,
    "otherfamilydescription"=>nil,
    "partnumber"=>"",
    "pnpdeviceid"=>nil,
    "powermanagementcapabilities"=>nil,
    "powermanagementsupported"=>false,
    "processorid"=>"1FABFBFF000306A9",
    "processortype"=>3,
    "revision"=>14857,
    "role"=>"CPU",
    "secondleveladdresstranslationextensions"=>false,
    "serialnumber"=>"",
    "socketdesignation"=>"CPU #000",
    "status"=>"OK",
    "statusinfo"=>3,
    "stepping"=>nil,
    "systemcreationclassname"=>"Win32_ComputerSystem",
    "systemname"=>"DESKTOP-M560PAN",
    "threadcount"=>nil,
    "uniqueid"=>nil,
    "upgrademethod"=>4,
    "version"=>"",
    "virtualizationfirmwareenabled"=>false,
    "vmmonitormodeextensions"=>false,
    "voltagecaps"=>2},
  @wmi_ole_object=#<WIN32OLE:0x000000044bc6d0>>]
```

Seems odd, though. `"description"=>"Intel64 Family 6 Model 58 Stepping 9"` and `"stepping"=>nil` disagree. Could be a problem with WMI or Win 10. Should we parse `"description"` for stepping if `"stepping" => nil`?

**Comment by sh9189** [comment]
I think its a problem with wmi. On my windows 7 machine I see no value returned for stepping even though stepping is in description.
C:\Users\skhajamohid1>wmic cpu Get/Format:List


AddressWidth=64
Architecture=9
Availability=3
Caption=Intel64 Family 6 Model 58 Stepping 9
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CpuStatus=1
CreationClassName=Win32_Processor
CurrentClockSpeed=2176
CurrentVoltage=11
DataWidth=64
Description=Intel64 Family 6 Model 58 Stepping 9
DeviceID=CPU0
ErrorCleared=
ErrorDescription=
ExtClock=100
Family=205
InstallDate=
L2CacheSize=1024
L2CacheSpeed=
L3CacheSize=6144
L3CacheSpeed=0
LastErrorCode=
Level=6
LoadPercentage=30
Manufacturer=GenuineIntel
MaxClockSpeed=3401
Name=Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
NumberOfCores=4
NumberOfLogicalProcessors=4
OtherFamilyDescription=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=FALSE
ProcessorId=BFEBFBFF000306A9
ProcessorType=3
Revision=14857
Role=CPU
SocketDesignation=Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
Status=OK
StatusInfo=3
Stepping=
SystemCreationClassName=Win32_ComputerSystem
SystemName=NY731-22-131A
UniqueId=
UpgradeMethod=36
Version=
VoltageCaps=

**Comment by sh9189** [comment]
@mcquin I patched the pull request to get stepping from description if stepping is nil from wmi. Please review.

**Comment by mcquin** [comment]
Great! Works for me.

:+1:

**Comment by sh9189** [comment]
cc @chef/client-windows

**Comment by mcquin** [comment]
Need another review from @chef/client-core

**Comment by thommay** [comment]
LGTM :+1: Some review from @chef/client-windows might be good too

**Comment by ksubrama** [comment]
:+1:

**Comment by danielsdeleo** [comment]
The code looks good to me. How much impact do we expect this change to cause though:

> Change cpu[:total] to return total number of logical processors instead of cores as in other platforms like Linux,Solaris

**Comment by btm** [comment]
Obviously if someone is relying on that in automated calculations that will cause issues for them, but I'm presuming we haven't crossed that bridge yet in the wild and @sh9189 was in the course of crossing it.

**Pull request merged**
