### PR TITLE
Add freebsd support in packages plugin

### PR DESCRIPTION
**Pull request by vr**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @vr

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
+1

**Comment by tas50** [comment]
Ping @mcquin

**Comment by tas50** [comment]
Ping @thommay as well

**Comment by thommay** [comment]
ping @chef/client-freebsd

**Comment by tas50** [comment]
I should add the query command works fine on my FreeBSD 10.3 and 9.3 hosts

**Comment by tas50** [comment]
So it's been pointed out to me that pkg only exists out of the box on FreeBSD 10.  We need to handle the shell out failure better and include some logging.  Right now the plugin will fail with a stack trace to debug.

**Comment by Aevin1387** [comment]
@tas50 FreeBSD 9.3 does support pkg if setup to use it, otherwise you would use pkgng. You can look at https://github.com/chef/chef/blob/c1a389c2a8452e9b796aa1d34c4d9e51f4af30c7/lib/chef/resource/freebsd_package.rb to see how the package resource checks for it.

**Comment by tas50** [comment]
@Aevin1387 It's not enabled by default though right?

**Comment by lamont-granquist** [comment]
this is better than nothing and would get support on freebsd 10 + up.  should probably make the exitstatus raise if the status is non-zero (and ideally implement shell_out! in the shell_out mixin, because its kind of aggravating not to have the same API in chef and ohai).

**Comment by smurawski** [comment]
👍

**Comment by lamont-granquist** [comment]
👍

**Comment by thommay** [comment]
👍

**Pull request merged**
