### PR TITLE
Update Ruby version + branches we build

### PR DESCRIPTION
**Pull request by tas50**
Also remove the builds of stable branches we don't use. We're never releasing 7 stable again.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by mcquin** [comment]
What prompted the decision to not build stable branches?

**Comment by tas50** [comment]
The stable branch model doesn't seem like a thing we're doing anymore.  At the very least we're never going to build 7.4-stable again.

**Comment by mcquin** [comment]
Sounds fair. Can we give this a name that also reflects the change to remove build versions?

**Comment by tas50** [comment]
@mcquin done

**Comment by mcquin** [comment]
Thanks! 👍

**Pull request merged**
