### PR TITLE
updating openstack plugin to have a timeout and actually return data

### PR DESCRIPTION
**Pull request by acaiafa**
not sure who this should goto. However I have verified the current plugin does not return any data what so ever.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by acaiafa** [comment]
Ok i will take a look at this spec. 

@mattray was there any reason you were forcing the hint for HP or OpenStack? 

Also if there is any need for the vendor_data as well I will munge that in. I want to grab the tenancy name which i think is super helpful which i am working in now.

**Comment by jjasghar** [comment]
@acaiafa the hint was for the knife-hp plugin back in the day. We haven't updated this since then, this is a great opportunity to revisit this code and clean it up.

**Comment by acaiafa** [comment]
@jjasghar ok cool yeah i am not going to include it. I updated my email for the committers stuff also. 

I have to fix the spec i guess? It may take a short while.

**Comment by pburkholder** [comment]
PR is covered by CCLA: https://supermarket.chef.io/ccla-signatures/357/contributors. Not sure how to get Curry to agree...

**Comment by tas50** [comment]
@acaiafa In its current form this is going to cause issues for a lot of users.  The reasons we've relied on hint data for clouds is that we don't want to hit the metadata endpoints when running on non-cloud systems.  Adding the wait period is a step in the right direction, but even with that this plugin firing and timing out is going to add 5 seconds to a non-Openstack user's run.  

We have some basic, but effective Openstack detection in the virtualization plugin that uses DMI data on FreeBSD / Linux systems. That detection logic could easily be expanded to additional platforms like Windows.  Using the data from this plugin along with the existing hint logic is probably the way to go.  Requiring that either the hint exists or the virtualization system is detected as Openstack would eliminate the absolute need for the hint, but prevent polling metadata endpoints unnecessarily.

**Comment by acaiafa** [comment]
@tas50 ok fair enough. Do you want me to add the hint back in?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
@acaiafa Take a look at the rspec failures in Travis

**Comment by acaiafa** [comment]
@tas50 yeah going to dig through those.

**Comment by tas50** [comment]
@acaiafa Any update on the tests?  I'd love to get this merged in so I can get going on improving the non-hint detection logic.

**Comment by tas50** [comment]
I've pulled your branch into my fork and I cleaned up a few things:

- Removed HP Cloud logic
- Ran chefstyle (our rubocop rules)
- Removed the rescue exception

https://github.com/tas50/ohai-1/tree/acaiafa-updating_openstack

**Comment by tas50** [comment]
Closing this in favor of #817

**Pull request closed without merging**
