### PR TITLE
Detect Azure when DHCP domain is set to reddog.microsoft.com

### LINKED ISSUE #1519: Windows nodes on Azure that do not have the WAAgent are not collecting Azure attributes
## Description

Currently Ohai uses the [WAAgent or DHCP option 245][1] as the primary means of detecting whether or not a node is in Azure. Unfortunately the detection of option 245 was [only implemented for Linux][2].

## Ohai Version

v16.4.16

## Platform Version

- Windows Server 2012R2
- Windows Server 2016

[1]: https://github.com/chef/ohai/blob/v16.4.16/lib/ohai/plugins/azure.rb#L37
[2]: https://github.com/chef/ohai/blob/v16.4.16/lib/ohai/plugins/azure.rb#L56-L68

### PR DESCRIPTION
**Pull request by jasonwbarnett**
## Description

This will detect that a node is on Azure if DHCP option 15 is set to `reddog.microsoft.com` which Microsoft does in Azure for all customers.

> When you are using Azure-provided name resolution, Azure Dynamic Host Configuration Protocol (DHCP) provides an internal DNS suffix (.internal.cloudapp.net) to each VM. This suffix enables host name resolution because the host name records are in the internal.cloudapp.net zone. When you are using your own name resolution solution, this suffix is not supplied to VMs because it interferes with other DNS architectures (like domain-joined scenarios). Instead, Azure provides a non-functioning placeholder (reddog.microsoft.com).

Reference: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances

## Related Issue

- Fixes #1519 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
I haven't written any unit tests, _yet_. I have tested this on an Azure host and a non-azure host and the code is working as expected.

I plan to write unit tests as soon as I get affirmation this implementation/strategy makes sense.

**Comment by jasonwbarnett** [comment]
@tas50 @phiggins Let me know if this is ready to rock and I'll get started on building out test coverage.

**Comment by tas50** [comment]
This seems like a pretty solid approach to me. Go for it.

**Comment by jasonwbarnett** [comment]
@tas50 this is ready for review. Let me know if there are any docs that need to be updated as a result of this change.

**Comment by tas50** [comment]
Thanks @jasonwbarnett

**Pull request merged**
