### PR TITLE
6 stable

### PR DESCRIPTION
**Pull request by ganeshnalawade**
Fixes issue #575 #576 and #577

### CODE REVIEW

**Comment by thommay** [comment]
hi @ganeshnalawade we almost certainly won't take changes to ohai 6; our development happens on master (which is currently ohai 8). Also, please could you split these changes so that there's one pull request per issue that you solve.
Thanks a lot for your contributions, and if I can help more please let me know.

**Comment by ganeshnalawade** [comment]
@thommay Ohai 6 version is used in Chef on JUNOS pacakge (https://www.juniper.net/support/downloads/?p=chefforjunos) hence i raised pull request on that branch.
Do you want me to raise separate pull request on master branch?

**Comment by thommay** [comment]
@ganeshnalawade please raise three separate pull requests, one per issue you're fixing, against master.  Thanks!

**Comment by btm** [comment]
Closing this in preference of individual PRs.

**Pull request closed without merging**
