### PR TITLE
OHAI-726 Regex to support openjdk 1.8

### PR DESCRIPTION
**Pull request by davidnewman**
This changes the regex to support the openjdk 1.8 version string change.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
@davidnewman Can you add a unit test that uses the openjdk 1.8 output so we can make sure we don't break this in the future.  There should be a nice example to use from the existing version output.

**Comment by davidnewman** [comment]
No problem! I added the tests. I don't know rspec, and I'm not a rubyist. I think I followed the existing pattern though.

**Comment by tas50** [comment]
@davidnewman We'll also need the CLA signed to avoid legal issues down the road.  There's information on the process in the contributing document in this repository.

**Comment by davidnewman** [comment]
@tas50 OK, I've now signed the ICLA.

**Comment by mcquin** [comment]
:+1: Code looks good!

**Comment by tas50** [comment]
:+1:

**Pull request merged**
