### PR TITLE
Avoid false detection of systems with the ec2 binary as ec2

### PR DESCRIPTION
**Pull request by tas50**
Ensure the ec2metadata bin actually returns data. Otherwise we're probably not on ec2

### CODE REVIEW

**Comment by tas50** [comment]
Confirmed this fixes false identification on GCE

**Comment by astoltz** [comment]
Fantastic! Thanks!

**Comment by mcquin** [comment]
:+1:

**Comment by tas50** [comment]
@chef/client-core This is ready for review

**Comment by coderanger** [comment]
This should also help with our misdetection of OpenStack instances outside of Rackspace. :+1: (but I'm not a maintainer)

**Comment by johnbellone** [comment]
I can test this tomorrow, but I am pretty sure that ec2metadata returns results on OpenStack.

**Comment by johnbellone** [comment]
We have a separate patch for GCE. When you have a honeypot name server the metadata address is caught and identities node as such.

**Comment by tas50** [comment]
It's looking for results that specify include 'ami-', which I hope Openstack doesn't include.

**Comment by tas50** [comment]
That being said I'd love to get this tested on Openstack.

**Comment by johnbellone** [comment]
```sh
jbellone@ip-1-71-19-11:~$ uname -a
Linux ip-1-71-19-11 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jbellone@ip-1-71-19-11:~$ /usr/bin/ec2metadata |grep ami
ami-id: ami-00000052
ami-launch-index: 0
ami-manifest-path: FIXME
ancestor-ami-ids: unavailable
block-device-mapping: ami
```

**Comment by tas50** [comment]
:(

**Comment by johnbellone** [comment]
```sh
jbellone@ip-1-71-19-11:~$ uname -a
Linux ip-1-71-19-11 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jbellone@ip-1-71-19-11:~$ /usr/bin/ec2metadata |grep ami
ami-id: ami-00000052
ami-launch-index: 0
ami-manifest-path: FIXME
ancestor-ami-ids: unavailable
block-device-mapping: ami
```

**Comment by johnbellone** [comment]
```sh
[jbellone@ip-1-71-19-4 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[jbellone@ip-1-71-19-4 ~]$ /usr/bin/ec2metadata |grep ami
ami-id: ami-00000011
ami-launch-index: 0
ami-manifest-path: FIXME
ancestor-ami-ids: unavailable
block-device-mapping: ami
```

**Comment by johnbellone** [comment]
Its same for RHEL instances as well. :(

**Comment by tas50** [comment]
@johnbellone Any chance you could sanitize the complete output from Openstack.  I'd like to use that for the tests once I come up with a better method.

**Comment by coderanger** [comment]
So two thoughts from sitting on the train. First, the whole point of having this elaborate detection for EC2 was to avoid making spurious network requests to the metadata server, but this patch does exactly that. It seems like we might as well do the HTTP get from Ohai directly, saves a few CPU cycles and easier to parse. Second, we can probably filter out both GCE and OpenStack by looking for VPC-related values, because non-VPC machines should be catchable on other detection routines.

**Comment by johnbellone** [comment]
@tas50 https://gist.github.com/johnbellone/0241fb3d96d418ccb2cfd9860733cf21

**Comment by johnbellone** [comment]
FWIW I am digging through some of the cloud config data... no idea what this is
```sh
root@ip-1-71-19-3:/var/lib/cloud/instance# cat obj.pkl |grep -i openstack
aS'OpenStack'
```

**Comment by tas50** [comment]
Back to the drawing board to find a reliable way to detect paravirt systems in a VPC.

**Comment by lamont-granquist** [comment]
One thing you can do is do a DNS lookup on "instance-data.ec2.internal" which will give you back a response fast.  You can't rule out being in EC2 but you can rule it in.

Another idea is that if ohai is running as root and it detects that it is running in EC2 via some method which is reliable that it should drop a hint file so it can pick it up next time.

Those two methods woudl work best together since on first-run it can DNS lookup "instance-data.ec2.internal" when it hits the default amazon nameservers, then it drops a hint file, then after the nameservers have been changed to 8.8.8.8 and the ""instance-data.ec2.internal" no longer works the hint file is still there.

Which suggests another tactic to use which is to do expensive-but-correct things and write out state data to avoid it.  That way you could implement things like hitting 'checkip.dyndns.org' and then doing a reverse DNS lookup on the public/NAT'd IP address to see if it resolves to amazonaws.com or not.

In general, abandon the idea of making ohai always run fast 100% of the time, and accept it taking longer and doing network connections the first time it runs.  Make it manage its own hint state.

**Comment by lamont-granquist** [comment]
I'm also thinking that a certain amount of policy may be applicable here.

- if you drop a hint file (that knife ec2 server create and such creates by default) then we can positively ID you as being in EC2
- if you are running an HVM we can use DMI to positively ID you has being in EC2
- if you fail both of those and are not running paravirt Xen (bare metal or any other hypervisor) then we know you're not EC2

The remaining use cases are slim, and should get slimmer as people SHOULD switch to HVM.

This could just be closed as a problem that we stop trying to solve, and remove all the metadata-endpoint-detection-code and aggressively point people at hinting.

I'm also thinking that most of the tactics I just outlined might better be stuck into a cookbook.  They're all expensive and could be opt-in.  Users who irrationally hate on hinting could be pointed at the 'ohaicloudwtfbbq' cookbook which could do all the work of finding your public/NAT IP, doing the reverse lookup and fixing your hints file for you.

**Comment by tas50** [comment]
So my goal is to avoid the user having to ever drop in a hint, which does put us in a position where we need accurate detection.  We just started adding hints in via provisioning yesterday, and not everyone uses knife-ec2 since it has a lot of rough edges, so 100% reliance on hints isn't realistic.  Hints should be the absolute last resort and we should use them more like we do hints in Azure where we load it with data since there is not metadata endpoint.  I would like to move us to a world where Ohai creates hints to save work on the next chef run. Once we know for certain we're on EC2, relying on hints is perfect. Making that happen is also pretty simple.

All that being said I'm going to close this PR out and open a new PR to remove the ec2metadata command line detection.  It's 100% wrong as is, and results in a lot of false detection.  I have a few other 100% ways to detect EC2 nodes and I'll handle those in other PRs.

**Pull request closed without merging**
