### PR TITLE
Make aix, solaris memory output consistent to linux, add spec test for linux memory

### PR DESCRIPTION
**Pull request by sh9189**
1. Make linux memory plugin output to be in megabytes, consistent with other platforms such as Solaris, AIX, Windows. This helps with writing any tool that read memory plugin attributes regardless of platforms. 
2. Add spec tests for the linux memory plugin

### CODE REVIEW

**Comment by thommay** [comment]
we probably can't take this until Chef 13 at the earliest, and it would break the entire world even then. :(

**Comment by sh9189** [comment]
@thommay, In that case, do you think that it is better to change the output of other platform's memory plugin to match that of Linux. That is less of a breaking change compared to this and I can change the pull request to do that and to add spec tests for linux memory plugin. For example in #606, I am changing kB to MB for Windows memory to be consistent with other platforms. and only recently did we fix memory plugin output on solaris through #591, #599 and on aix through #598 and #602. These changes are not released yet so I doubt anyone is relying on them and memory plugins on other platforms (AIX,Solaris,Windows) were not available before these pull requests. Let me know your thoughts.

**Comment by thommay** [comment]
yeah, i think KB across the board might be better. Sorry for making you do additional work.

**Comment by sh9189** [comment]
@thommay  I have made changes so that memory plugin output is consistent across AIX,Solaris and Linux. Please review

**Comment by sh9189** [comment]
@thommay With the latest changes, can we consider this as a patch to be merged to master instead of "Accepted Major" milestone?

**Comment by thommay** [comment]
LGTM :+1: - @chef/client-maintainers

**Comment by mcquin** [comment]
:+1:

**Comment by sh9189** [comment]
@mcquin @thommay  Can this be marked "Ready for Merge" or does it need more review?

**Comment by btm** [comment]
:+1:

I've reviewed the changes and I'm pretty sure they're not breaking any existing release, so this could go out in a minor.

I'm a little sad that we're pushing out the unit with the data, such that you've got to strip it if you want to do any arithmetic with the data. OTOH, it makes it a little "not our problem" if some values are in different units and we're letting people know what the units are.

**Pull request merged**
