### PR TITLE
Backport 947a97d47daa1dce6aa7b91f2057b15451805b25

### PR DESCRIPTION
**Pull request by mvangoor**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@mvangoor This will require a DCO sign off before we can merge it, but otherwise this looks great. Thanks

**Comment by mvangoor** [comment]
@tas50 Should be signed off now

**Comment by Xorima** [comment]
Do we need to have almalinux as well?

**Comment by tas50** [comment]
We should make sure the 2 files basically match 17->16

**Pull request merged**
