### PR TITLE
mime-types 3 is Ruby 2.0+ only

### PR DESCRIPTION
**Pull request by halostatue**
This was released on the 2015-11-21.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @halostatue

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by thommay** [comment]
Obvious fix.

**Comment by tas50** [comment]
@halostatue Looks like you deleted the branch for this change before we could merge it.

**Comment by halostatue** [comment]
@tas50 See issue #651. I’m not interested in signing the CLA for such a trivial fix.

**Comment by thommay** [comment]
@halostatue you don't need to - we have an obvious fix policy for such things, so if you can recreate the branch we can just merge it. Thanks :)

**Comment by halostatue** [comment]
There you go.

**Comment by thommay** [comment]
:+1: @chef/client-core for more thumbs

**Comment by mcquin** [comment]
:+1:

**Pull request merged**
