### PR TITLE
Release 8.17.0

### PR DESCRIPTION
**Pull request by tas50**
Let's make sure we get our recent changes into the next Chef release.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
👍 other than appveyor angry

**Comment by thommay** [comment]
👍 appveyor is unrelated and being worked on

**Comment by jaymzh** [comment]
:+1:

**Comment by btm** [comment]
:+1:

Is there a plan to reversion ohai per [rfc076](https://github.com/chef/chef-rfc/blob/master/rfc076-reversion-ohai.md)?

**Comment by tas50** [comment]
@btm I'd like to get the reversioning done and get auto bumping setup similar to what we're doing in chef/chef.

**Pull request merged**
