### PR TITLE
release 8.15.0

### PR DESCRIPTION
**Pull request by mwrock**
This is needed for incoming changes to chef-client related to the FIPS plugin

### CODE REVIEW

**Comment by tas50** [comment]
It would be great if we could wait until we merge in #802 #801 to ship this version

**Comment by mwrock** [comment]
I just +1'd both and I can regenerate the changelog here after you merge those.

**Comment by mwrock** [comment]
regenerated changelog @tas50

**Comment by tas50** [comment]
🚢

**Comment by mcquin** [comment]
🚀

**Pull request merged**
