### PR TITLE
improve packages attribute. #819

### PR DESCRIPTION
**Pull request by glensc**
improve packages attribute. #819

- rpm: add epoch, arch
- deb: add arch

i tried to explode the version component on debian systems, but wasn't sure what are the component parts:

- 3.4.2-1
- 1:1.0.9-1
- 4.1+Debian13+nmu1
- 5.1.1alpha+20120614-2+b3

rpm has `%{INSTALLTIME}`, add it as `installdate` attribute? but what format? unix timestamp? (it's the easiest one)

(tests are expected to fail, until get some feedback)

### CODE REVIEW

**Comment by glensc** [comment]
| ${Version} | epoch | version | release |
| ------------- | ------------- | ------------- | ------------- |
| 3.4.2-1 | nil | 3.4.2 | 1 |
| 1:1.0.9-1 | 1 | 1.0.9 | 1 |
| 4.1+Debian13+nmu1 | nil | ? | ? |
| 5.1.1alpha+20120614-2+b3 | nil | ? | ? |

**Comment by glensc** [comment]
found some documentation of Debian ${Version} components: http://linux.die.net/man/5/deb-version

seems not very simplie split and go logic here... suggestions?

**Comment by glensc** [comment]
for consistency should deb/rpm use or not to use `shellwords`. i would drop the shellwords because the input is fixed string (not containing user input).

**Comment by mcquin** [comment]
Can someone from @chef/client-ubuntu lend a hand to answer @glensc question at https://github.com/chef/ohai/pull/820#issuecomment-218443156

**Comment by lamont-granquist** [comment]
i think shellwords is likely there to prevent shell expansion of special characters in the string in question so that you don't have to go insane thinking about everything you'd need to backwhack, not necessarily about security...

**Comment by glensc** [comment]
my string is between `''`, so it's never expanded

**Comment by lamont-granquist** [comment]
👍

**Comment by lamont-granquist** [comment]
spec test need to be updated to make it pass, its failing everything right now

**Comment by glensc** [comment]
@lamont-granquist i specifically wrote in summary:
> (tests are expected to fail, until get some feedback)

and haven't got the necessary feedback!

**Comment by glensc** [comment]
so, i assume nobody (from ohai maintainers) cares what the result is and will be merged as is? i'm personally are satisfied with current result of this PR.

**Comment by glensc** [comment]
also, how do you expect me to update the unit test?
 
replace `spec/data/plugins/dpkg-query.output` and `spec/data/plugins/rpmquery.output` from my system?

**Comment by glensc** [comment]
rpm data replaced with output from

`docker run --rm -it centos bash`

and truncated it

**Comment by lamont-granquist** [comment]
yeah that looks fine, i'd prefer to have slightly tighter fixtures so it was more obvious what was important and what wasn't...

**Comment by glensc** [comment]
so, ready for merge?

**Comment by lamont-granquist** [comment]
👍

**Comment by lamont-granquist** [comment]
@thommay whack merge if you're satisfied...

**Comment by thommay** [comment]
thanks, @glensc!

**Pull request merged**
