### PR TITLE
Don't enable packages plugin by default

### PR DESCRIPTION
**Pull request by jaym**
This is a hack. We can make this into a proper
DSL thing where specifying something like `default_enabled false`.

For now, this could be enabled through

```ruby
ohai[:plugins][:packages][:enabled] = true
```

I want to make sure we don't back ourselves into a situation where we want/need to make a breaking change. This is a possible alternative to completely reverting the change, though I feel it may conflict with the idea of `disabled_plugins`.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i think `disabled_plugins` is also a hack, this actually looks a bit better to me...

**Comment by lamont-granquist** [comment]
https://github.com/chef/ohai/pull/717/files?w=0 for easier review

**Comment by danielsdeleo** [comment]
The consensus we came to for disabling the pnp plugin by default was to remove it from the tree and put it in a plugin. We should follow the same procedure everywhere, though personally I'm not invested in which one we choose.

**Comment by mwrock** [comment]
:+1:

**Comment by jaym** [comment]
we should definitely follow the same pattern for everything we do. I think having an ohai extra's cookbook has its benefits. Shipping it external to Chef probably means we can iterate faster. It has the downside that it may be a little harder to use.

perhaps we should revert for now, and RFC to figure out if people have a strong preference.

**Comment by lamont-granquist** [comment]
I actually like this approach.  I'd prefer it to look like this, tho:

```ruby
Ohai.plugin(:Packages) do
  enabled false  # defaults to true
  collect_data(:linux) do  # automagically checks configuration(enabled)
  end
end
```

**Comment by jaym** [comment]
Right, and it fits nicely with parts of https://github.com/chef/chef-rfc/pull/183

**Comment by lamont-granquist** [comment]
Yeah i think we also discussed deprecating `disabled_plugins` along with the RFC for ohai configuration.  That could be tied nicely into this.

**Comment by danielsdeleo** [comment]
For the long term, I guess we could have "optional_attributes" be a thing and you would request them via attribute paths, e.g., `optional_attributes "packages", "windows/pnp"`. It'd be a breaking change to mark a bunch of existing things as optional, so we could make a breaking config language change at the same time. If everyone is cool with this as a first effort, then I'm :+1: But we need to figure out what to do about *nix for this change as the travis tests are pointing out. Is it just windows package listing that's new, or is the whole plugin new?

**Comment by lamont-granquist** [comment]
whole plugin is new

**Comment by danielsdeleo** [comment]
Should we make it "optional" for everyone then?

**Comment by jaym** [comment]
@danielsdeleo i'm not sure that we need `optional_attributes`. https://github.com/chef/chef-rfc/blob/master/rfc053-ohai-config.md covers the configuration i think

**Comment by jaym** [comment]
Oh, I see, that's for like chef configuration?

**Comment by danielsdeleo** [comment]
@jaym yeah, the idea is that some plugins would be marked "optional" and would be opt-in, then you would enable them via configuration somewhere that says "I expect ohai to collect these attributes when it runs"

**Comment by lamont-granquist** [comment]
i would like to get to requested attributes driving enabled plugins.  for now i think just having switches at the plugin level and exposed in the configuration settings is good enough to move the ball forwards.

**Comment by btm** [comment]
I'd prefer that we disable the "bad" plugins but leave them in ohai, and use a configuration value (rfc035 compliant) in the chef configuration (client.rb) to re-enable them if the user chooses.

the only downside is it is a little painful to get those configuration values into your client.rb right now but https://github.com/chef/chef-rfc/pull/183 should solve that and was the next step on the roadmap I laid out in the rfc035 discussion that diverted into an ohai hints / UX discussion.

mostly because this will be a completely reasonable pattern, and as we get closer to being able to easily configure ohai via Chef, its going to be very valuable and Right[tm] for all choices.

**Comment by lamont-granquist** [comment]
Also at some point in the future we can disable all the plugins by default, and then the requested_attributes feature can selectively enable and run the plugins as necessary...  I think this is a step in that direction.

**Comment by btm** [comment]
@lamont-granquist exactly. by 2025 we will have completed the entire roadmap we originally had for ohai 7.

**Comment by jaym** [comment]
The plan is to merge this. We want to take Ohai in this direction, and hence this concept can be generalized into all of Ohai without making a breaking change in the future.

**Comment by tyler-ball** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
