### PR TITLE
Relax restriction on chef dependency.

### PR DESCRIPTION
**Pull request by ksubrama**
During omnibus builds, bundler --without development still downloads all
dependencies specified so that it can resolve versions consistently
regardless of which install groups are specified.  If ohai pins a
chef dependency to chef master, then any changes to chef master that
pull in a different version of ohai will impact our ability to bundle
install our dependencies.

### CODE REVIEW

**Comment by mcquin** [comment]
I'm :+1:, as `chef` is a development dependency in the gemspec anyway.

**Comment by tyler-ball** [comment]
:+1:

**Comment by schisamo** [comment]
:+1: assuming you fix the CI/merge failures above

**Comment by ksubrama** [comment]
I'm not going to merge at all :)  This was just a convenient way to show the diff.  The version bumps and stuff don't need to go into master.

**Comment by thommay** [comment]
@ksubrama if you don't want to merge this can we close it now?

**Pull request closed without merging**
