### PR TITLE
Fix some lint cops:

### PR DESCRIPTION
**Pull request by thommay**
1 Lint/EndAlignment
3 Lint/BlockAlignment

### CODE REVIEW

**Comment by thommay** [comment]
@chef/client-core @tas50 @mcquin

**Comment by tas50** [comment]
+1

**Comment by danielsdeleo** [comment]
:+1:

**Comment by lamont-granquist** [comment]
i'm working on fixing a couple more that were just added...

**Comment by mcquin** [comment]
:ship:

**Pull request merged**
