### PR TITLE
Ohai shell_out logging, timeouts, and error handling

### PR DESCRIPTION
**Pull request by mcquin**
Modify ohai's shell_out to provide basic logging of command exit status and failures. Adds a default 30s timeout to all commands. 

Replaces https://github.com/chef/ohai/pull/732

### CODE REVIEW

**Comment by mcquin** [comment]
Ready for review @chef/client-core

**Comment by jaymzh** [comment]
:+1: :cry: 
(that's "I'm so happy I'm crying")

You are doing the lord's work. :)

**Comment by mcquin** [comment]
You won't believe what happens next @jaymzh ;)

**Comment by tas50** [comment]
:+1: Merge it!

**Comment by jaymzh** [comment]
You planning to update all of the plugins?

**Comment by tas50** [comment]
Yep.  The goal here, besides the timeout, was to make the debug output useful and not full of stack traces

**Pull request merged**
