### PR TITLE
Update Azure cloud plugin to query server for data instead of reading th...

### PR DESCRIPTION
**Pull request by akarpik**
Update Azure cloud plugin to query server for data instead of reading them form hint file.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@adamedx had a lot of concerns about this whole approach, the dhcp server isn't necessarily a metadata server and its reponses can't be considered to be reliable.

**Comment by lamont-granquist** [comment]
@btm ping

**Comment by adamedx** [comment]
@jeffmendoza, @nimishas, is this approach a valid way to query Azure for metadata? There is no formal metadata service from what I can tell for Azure. This also appears to be limited to Linux and won't handle the Windows case.

**Comment by jeffmendoza** [comment]
@johngossman do you want to take a look? We had discussed a solution of looking in /var/lib/waagent/SharedConfig.xml in the past. Not sure about this dhcp solution.

**Comment by akarpik** [comment]
@jeffmendoza, basically /var/lib/waagent/SharedConfig.xml solution is only available for Linux. That is why we have decided to find another way to get this data.

**Comment by lamont-granquist** [comment]
can we close this?

**Comment by akarpik** [comment]
@lamont-granquist you want to merge and close, or just close?

**Comment by akarpik** [comment]
So what is going on with this pull request?

**Comment by thommay** [comment]
@akarpik it looks like the consensus is to close this, so I am doing so.

**Pull request closed without merging**
