### PR TITLE
Removed chef as development_dependency in gemspec as it is already li…

### PR DESCRIPTION
**Pull request by tylercloke**
…sted in Gemfile development block.

### CODE REVIEW

**Comment by mcquin** [comment]
I believe this is going to cause problems once the version in chef/chef master is 13, because of [this dependency](https://github.com/chef/ohai/blob/master/ohai.gemspec#L36).

**Comment by lamont-granquist** [comment]
I think the only difference between the two is that dev gems listed in the gemspec show up on rubygems, while dev gems in Gemfile's give you the ability to pull from github and such.  We probably do want to have it only in one place, and most likely want it in the Gemfile since we need the flexibility to pull from GH.

**Comment by smurawski** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
